[build]
  publish = "dist"
  command = "npm install --force && npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force"
  # Environment variables are now in .env.production file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200